[package]
name = "dg_utils"
version = "0.0.0"
authors = ["Karl Sundequist Blomdahl <karl.sundequist.blomdahl@gmail.com>"]
license = "Apache-2.0"
publish = false

[lib]
path = "lib.rs"
name = "dg_utils"
crate-type = ["lib"]

[dependencies]
dashmap = "4.0"
lazy_static = "1.4"
regex = "1.3"
